<?php

namespace AppBundle\Repository;

/**
 * AbonneesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneesRepository extends \Doctrine\ORM\EntityRepository
{
}
